

SECTION_STATION_TAKEOVER_DIVIDER = "STACJE ŁADOWANIA - DANE"
SECTION_CONTACT_PERSON = "OSOBA KONTAKTOWA - EKSPLOATACJA STACJI"
SECTION_RESPONSIBLE_PERSON = "OSOBA ODPOWIEDZIALNA ZA PRZEJĘCIE STACJI PO STRONIE KLIENTA"