

SECTION_STATION_TAKEOVER_DIVIDER = ["STACJA ŁADOWANIA – DANE", "STACJA ŁADOWANIA - DANE"]
SECTION_CONTACT_PERSON = ["OSOBA KONTAKTOWA - EKSPOLATACJA STACJI", "OSOBA KONTAKTOWA - EKSPLOATACJA STACJI"]
SECTION_RESPONSIBLE_PERSON = ["OSOBA ODPOWIEDZIALNA ZA PRZEJĘCIE STACJI PO STRONIE KLIENTA"]